Repository sparcs-kaist/biseo, pull requests merged in 2024-03, with the labels that each got.

#469 feat: align tags center
  packages/web/src/components/molecules/AdminAgendaTags.tsx
Labels: FE

#474 fix: vertically center username in profile popup
  packages/web/src/components/molecules/Profile.tsx
Labels: FE

#478 feat/chat date divider
  packages/web/src/components/organisms/ChatSection.tsx
  packages/web/src/utils/format.ts
Labels: FE, Chat

#472 fix: update .env.example
  packages/api/prisma/schema.prisma
Labels: bug
